  
using System;
using System.Collections.Generic;
namespace SolutionWeb.Model.POLICY
{
	public partial class BASE_WORKFLOW_INFO{
		public BASE_WORKFLOW_INFO ToPOCO(){
		return new BASE_WORKFLOW_INFO(){
				SID = SID,
				ITEM_TYPE = ITEM_TYPE,
				STATUS_NAME = STATUS_NAME,
				STATUS_CODE = STATUS_CODE,
				HANDLE_RESULT = HANDLE_RESULT,
				NEXT_STATUS_NAME = NEXT_STATUS_NAME,
				NEXT_STATUS_CODE = NEXT_STATUS_CODE,
				TIME_LIMIT = TIME_LIMIT,
				BUTTONS_VALUE = BUTTONS_VALUE,
				BUTTONS = BUTTONS,
				BACK_STEP = BACK_STEP,
				PREVIOUS_STEP = PREVIOUS_STEP,
				NEXT_STEP = NEXT_STEP,
				IS_SEAL = IS_SEAL,
				IS_HAS_FILE = IS_HAS_FILE,
				DEFAULT_HANDLER = DEFAULT_HANDLER,
				BACK_CLASS = BACK_CLASS,
				COUNTERSIGN = COUNTERSIGN,
			};
		}
	}
}  
