  
using System;
using System.Collections.Generic;
namespace SolutionWeb.Model.POLICY
{
	public partial class CORPORATION_BASE_INFO{
		public CORPORATION_BASE_INFO ToPOCO(){
		return new CORPORATION_BASE_INFO(){
				SID = SID,
				CREATE_DT = CREATE_DT,
				CREATE_BY = CREATE_BY,
				UPDATE_DT = UPDATE_DT,
				UPDATE_BY = UPDATE_BY,
				CORP_NAME = CORP_NAME,
				SOCIAL_CREDIT_CODE = SOCIAL_CREDIT_CODE,
				REGISTERED_ADDRESS = REGISTERED_ADDRESS,
				LEGAL_PERSON = LEGAL_PERSON,
				LEGAL_PERSON_PHONE = LEGAL_PERSON_PHONE,
				OPERATOR = OPERATOR,
				OPERATOR_PHONE = OPERATOR_PHONE,
				OPERATOR_ID_NO = OPERATOR_ID_NO,
				EMIAL = EMIAL,
				REGISTERED_CAPITAL = REGISTERED_CAPITAL,
				USER_NAME = USER_NAME,
				PASSWORD = PASSWORD,
				CORP_STATUS = CORP_STATUS,
				APPLY_RESULT = APPLY_RESULT,
			};
		}
	}
}  
