  
using System;
using System.Collections.Generic;
namespace SolutionWeb.Model.POLICY
{
	public partial class POLICY_STATUS_CHANGE{
		public POLICY_STATUS_CHANGE ToPOCO(){
		return new POLICY_STATUS_CHANGE(){
				SID = SID,
				POLICY_SID = POLICY_SID,
				DEPT_CODE = DEPT_CODE,
				ITEM_TYPE = ITEM_TYPE,
				STATUS_NAME = STATUS_NAME,
				STATUS_CODE = STATUS_CODE,
				CREATE_DT = CREATE_DT,
				HANDLE_SID = HANDLE_SID,
				HANDLE_DT = HANDLE_DT,
				HANDLE_RESULT = HANDLE_RESULT,
				HANDLE_CONTENT = HANDLE_CONTENT,
				IS_HANDLE = IS_HANDLE,
				IS_CALCULATE = IS_CALCULATE,
				CALCULATE_DT = CALCULATE_DT,
				TIME_LIMIT = TIME_LIMIT,
				HANDLE_NAME = HANDLE_NAME,
				DEPT_NAME = DEPT_NAME,
				IS_VOTE = IS_VOTE,
				SEAL_SID = SEAL_SID,
			};
		}
	}
}  
