  
using System;
using System.Collections.Generic;
namespace SolutionWeb.Model.POLICY
{
	public partial class POLICY_MAIN_INFO{
		public POLICY_MAIN_INFO ToPOCO(){
		return new POLICY_MAIN_INFO(){
				SID = SID,
				CREATE_DT = CREATE_DT,
				CREATE_BY = CREATE_BY,
				UPDATE_DT = UPDATE_DT,
				UPDATE_BY = UPDATE_BY,
				APPLY_NUMBER = APPLY_NUMBER,
				STATUS_NAME = STATUS_NAME,
				STATUS_CODE = STATUS_CODE,
				CORPORATION_SID = CORPORATION_SID,
				CORP_NAME = CORP_NAME,
				SOCIAL_CREDIT_CODE = SOCIAL_CREDIT_CODE,
				REGISTERED_ADDRESS = REGISTERED_ADDRESS,
				LEGAL_PERSON = LEGAL_PERSON,
				LEGAL_PERSON_PHONE = LEGAL_PERSON_PHONE,
				OPERATOR = OPERATOR,
				OPERATOR_PHONE = OPERATOR_PHONE,
				OPERATOR_ID_NO = OPERATOR_ID_NO,
				EMIAL = EMIAL,
				REGISTERED_CAPITAL = REGISTERED_CAPITAL,
				APPLY_ITEM_TYPE = APPLY_ITEM_TYPE,
				APPLY_ITEM_NAME = APPLY_ITEM_NAME,
				APPLY_MONEY_WORDS = APPLY_MONEY_WORDS,
				APPLY_MONEY_NUMBER = APPLY_MONEY_NUMBER,
				APPLY_DT = APPLY_DT,
				APPLY_STATUS = APPLY_STATUS,
				DATA_STATUS = DATA_STATUS,
				BANK_NAME = BANK_NAME,
				BANK_ACOUNT = BANK_ACOUNT,
				CORP_PROMISE = CORP_PROMISE,
				VAT_NO = VAT_NO,
				COMPANY_NAME = COMPANY_NAME,
				POLICITY_STATUS = POLICITY_STATUS,
				POLICITY_BEGIN_DT = POLICITY_BEGIN_DT,
				POLICITY_END_DT = POLICITY_END_DT,
				POLICITY_STOP_REASON = POLICITY_STOP_REASON,
				IS_FILE = IS_FILE,
				FILE_DT = FILE_DT,
				COMPANY_ADDRESS = COMPANY_ADDRESS,
				COMPANY_PHONE = COMPANY_PHONE,
				REJECT_REASON = REJECT_REASON,
			};
		}
	}
}  
